#pragma once

#define HOSTNAME "marantz"

#define TIMER_SIGNAL 0
#define TIMER_NETWORK_CHECK 1
#define TIMER_LED_BLINK 2

#define SERVER_PORT 80
#define INTERRUPT_INTERVAL_MICROS 889
#define DATA_PIN 16
#define LED_PIN 2
#define WIFI_CONNECTION_TIMEOUT 5
#define WIFI_CHECK_INTERVAL 10000000
#define MDNS_MAX_TRIES 5
#define MDNS_RETRY_TIMEOUT 1000
#define LED_BLINK_INTERVAL_MICROS 500000